---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    pull: always
    image: golang:1.14
    commands:
      - apt-get update && apt-get install xz-utils
      - make lint
      - git diff --exit-code

  - name: test
    pull: always
    image: golang:1.14
    commands:
      - make test

  - name: build
    pull: always
    image: golang:1.14
    commands:
      - make build
